repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
    - id: markdownlint
  - repo: https://github.com/facelessuser/pyspelling
    rev: master
    hooks:
      - id: pyspelling
