matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - dictionaries/jekyll-chirpy-dictionary.txt
    - dictionaries/en-custom-dictionary.txt
    - dictionaries/about-page-dictionary.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - :matches(code, pre)
  sources:
  - '**/*.md'
  default_encoding: utf-8
