name: Markdown Lint
on:
  push:  # Trigger on any push to any branch
  pull_request:  # Trigger on any pull request to any branch

jobs:
    markdownlint-cli:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: markdownlint-cli
          uses: nosborn/github-action-markdown-cli@v3.4.0
          with:
            files: .
